development:
  adapter: postgresql
  encoding: unicode
  database: url-shortener-developer
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: url-shortener-product
  pool: 5
  url: <%=ENV['DATABASE_URL']%>